# vagrant box add --name rhel6_9 http://dogfood.sat.engineering.redhat.com/pulp/isos/Sat6-CI/Library/custom/Vagrant_Boxes/RHEL_Boxes/rhel-6.9_x86_64-server.box
# vagrant ssh -- -A -R 8080:localhost:8080
Vagrant.configure("2") do |config|
  config.vm.box = "rhel6_9"
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 4096
    libvirt.cpus = 6
    libvirt.qemu_use_session = false
  end

  config.vm.hostname = "rhel6-insights-client.virbr0.akofink-laptop"
  # config.vm.network "private_network", type: "dhcp"
  # config.vm.synced_folder "~/dev/repos/insights-client", "/home/vagrant/insights-client", type: "nfs", nfs_version: 4
  # config.vm.synced_folder "~/dev/repos/insights-core", "/home/vagrant/insights-core", type: "nfs", nfs_version: 4
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "insights-client.yml"
    ansible.extra_vars = {
      rhsm_password: ENV['RHSM_PASSWORD'] || ''
    }
  end
end
