---
- hosts: all
  tasks:
    - name: register with subscription-manager
      become: true
      redhat_subscription:
        server_hostname: https://subscription.rhsm.stage.redhat.com
        # server_hostname: https://subscription.rhsm.qa.redhat.com
        server_insecure: true
        username: rhn-engineering-akofink
        password: redhat
        force_register: true
        pool_ids:
          - 8a85f98c60c4fc0e0160c50f8b23045d

    - name: enable RH repositories
      become: true
      command: subscription-manager repos --enable rhel-7-server-rpms
    #   rhsm_repository: # does not work :(
    #     name: rhel-7-server-rpms

    - name: install epel
      become: true
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

    - name: install system dependencies
      become: true
      yum:
        name: openscap-scanner, scap-security-guide, make, rpm-build, python2-devel, sudo, git

    - name: install pip
      become: true
      command: easy_install pip

    - name: "run oscap for ds"
      command: "oscap xccdf eval --profile {{ item }} --results rhel7-{{ item }}.xml /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml"
      ignore_errors: true
      args:
        creates: "rhel7-{{ item }}.xml"
      loop:
        - xccdf_org.ssgproject.content_profile_pci-dss
        - xccdf_org.ssgproject.content_profile_ospp42
        - xccdf_org.ssgproject.content_profile_nist-800-171-cui
        - xccdf_org.ssgproject.content_profile_stig-rhel7-disa
        - xccdf_org.ssgproject.content_profile_rht-ccp
        - xccdf_org.ssgproject.content_profile_hipaa
        - xccdf_org.ssgproject.content_profile_ospp
        - xccdf_org.ssgproject.content_profile_standard
        - xccdf_org.ssgproject.content_profile_C2S
        - xccdf_org.ssgproject.content_profile_cjis
        - standard
        - hipaa

    - name: clone insights-client and insights-core repos
      git:
        repo: "https://github.com/RedHatInsights/{{ item }}.git"
        dest: "/home/vagrant/{{ item }}"
      args:
        creates: "/home/vagrant/{{ item }}"
      loop:
        - insights-client
        - insights-core

    - name: install insights-client
      become: true
      command: sh lay-the-eggs.sh
      args:
        chdir: /home/vagrant/insights-client

    - name: update config
      become: true
      blockinfile:
        path: /etc/insights-client/insights-client.conf
        block: |
          authmethod=BASIC
          username=rhn-engineering-akofink
          password=redhat
          #upload_url=https://ci.cloud.redhat.com/api/ingress/v1/upload
          cert_verify=False
          upload_url=http://localhost:8080/api/ingress/v1/upload
          auto_config=False
          auto_update=False
          legacy_upload=False
          debug=True

    - name: Install insights from local filesystem via pip
      become: true
      pip:
        name: file:///home/vagrant/insights-core#egg=insights
        extra_args: "-I"
    - name: set motd
      become: true
      blockinfile:
        path: /etc/motd
        block: |
          # Some useful example commands:
          sudo BYPASS_GPG=true insights-client --no-gpg --payload ~/rhel7-xccdf_org.ssgproject.content_profile_standard.xml --content-type application/vnd.redhat.compliance.something+tgz --net-debug --verbose
          find ~/rhel7-xccdf_org.ssgproject.content_profile_*.xml | xargs -I{} sudo BYPASS_GPG=true insights-client --no-gpg --payload {} --content-type application/vnd.redhat.compliance.something+tgz --net-debug
          sudo INSIGHTS_GPG=false BYPASS_GPG=true EGG=~/insights-core python ~/insights-client/insights_client/__init__.py --net-debug --verbose --payload ~/rhel7-xccdf_org.ssgproject.content_profile_standard.xml --content-type application/vnd.redhat.compliance.something+tgz
...
