---
- hosts: all
  tasks:
    - name: register with subscription-manager
      become: true
      command: subscription-manager register --username rhn-engineering-akofink --password redhat --serverurl https://subscription.rhsm.stage.redhat.com --auto-attach --force
      # redhat_subscription: # does not work yet -> https://github.com/ansible/ansible/pull/54815
      #   state: present
      #   username: rhn-engineering-akofink
      #   password: redhat
        # server_hostname: https://subscription.rhsm.stage.redhat.com
        # server_insecure: true
        # password: redhat
        # force_register: true
        # pool_ids:
        #   - 8a85f98c60c4fc0e0160c50f8b23045d

    # - name: enable RH repositories
    #   become: true
    #   command: subscription-manager repos --enable rhel-8-for-x86_64-baseos-rpms rhel-8-for-x86_64-appstream-rpms
    #   rhsm_repository:
    #     name: rhel-8-for-x86_64-baseos-rpms rhel-8-for-x86_64-appstream-rpms

    - name: install epel
      become: true
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm

    # - name: install system dependencies
    #   become: true
    #   yum:
    #     name: openscap-scanner, scap-security-guide, make, rpm-build, python2-devel, sudo, git

    # - name: install pip
    #   become: true
    #   command: easy_install pip

    #- name: "run oscap for ds"
    #  command: "oscap xccdf eval --profile {{ item }} --results rhel8-{{ item }}.xml /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml"
    #  ignore_errors: true
    #  args:
    #    creates: "rhel8-{{ item }}.xml"
    #  loop:
    #    - xccdf_org.ssgproject.content_profile_pci-dss
    #    - xccdf_org.ssgproject.content_profile_ospp42
    #    - xccdf_org.ssgproject.content_profile_nist-800-171-cui
    #    - xccdf_org.ssgproject.content_profile_stig-rhel7-disa
    #    - xccdf_org.ssgproject.content_profile_rht-ccp
    #    - xccdf_org.ssgproject.content_profile_hipaa
    #    - xccdf_org.ssgproject.content_profile_ospp
    #    - xccdf_org.ssgproject.content_profile_standard
    #    - xccdf_org.ssgproject.content_profile_C2S
    #    - xccdf_org.ssgproject.content_profile_cjis

    #- name: install insights-client
    #  become: true
    #  command: sh lay-the-eggs.sh
    #  args:
    #    chdir: /home/vagrant/insights-client

    #- name: update config
    #  become: true
    #  blockinfile:
    #    path: /etc/insights-client/insights-client.conf
    #    block: |
    #      #upload_url=https://ci.cloud.paas.psi.redhat.com/api/ingress/v1/upload
    #      cert_verify=False
    #      upload_url=http://localhost:8080/api/ingress/v1/upload
    #      auto_config=False
    #      auto_update=False
    #      legacy_upload=False

    #- name: Install insights from local filesystem via pip
    #  become: true
    #  pip:
    #    name: file:///home/vagrant/insights-core#egg=insights
    #    extra_args: "-I"
    #- name: set motd
    #  become: true
    #  blockinfile:
    #    path: /etc/motd
    #    block: |
    #      sudo BYPASS_GPG=true insights-client --no-gpg --payload ~/rhel7-xccdf_org.ssgproject.content_profile_standard.xml --content-type application/vnd.redhat.compliance.something+tgz --net-debug --verbose
    #      find ~/rhel7-xccdf_org.ssgproject.content_profile_*.xml | xargs -I{} sudo BYPASS_GPG=true insights-client --no-gpg --payload {} --content-type application/vnd.redhat.compliance.something+tgz --net-debug
...
