---
- hosts: all
  tasks:
    - name: register with subscription-manager
      become: true
      redhat_subscription:
        # server_hostname: https://subscription.rhsm.stage.redhat.com
        # server_insecure: true
        username: rhn-engineering-akofink
        password: "{{ rhsm_password }}"
        force_register: true
        pool_ids:
          - 8a85f98c60c4fc0e0160c50f8b23045d
    - name: enable RH repositories
      rhsm_repository:
        name: rhel-7-server-rpms
    - name: install epel
      become: true
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - name: install system dependencies
      become: true
      yum:
        name: openscap-scanner, scap-security-guide, sudo, insights-client
    - name: install pip
      become: true
      command: easy_install pip
    - name: "run oscap for ds"
      command: "oscap xccdf eval --profile {{ item }} --results rhel7-{{ item }}.xml /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml"
      ignore_errors: true
      args:
        creates: "rhel7-{{ item }}.xml"
      loop:
        - xccdf_org.ssgproject.content_profile_stig-rhel7-disa
        - xccdf_org.ssgproject.content_profile_ospp
        - xccdf_org.ssgproject.content_profile_pci-dss
        - xccdf_org.ssgproject.content_profile_rht-ccp
        - xccdf_org.ssgproject.content_profile_C2S
        - xccdf_org.ssgproject.content_profile_ospp42
        - xccdf_org.ssgproject.content_profile_cjis
        - xccdf_org.ssgproject.content_profile_standard
        - xccdf_org.ssgproject.content_profile_rhelh-vpp
        - xccdf_org.ssgproject.content_profile_hipaa
        - xccdf_org.ssgproject.content_profile_nist-800-171-cui
    - name: set motd
      become: true
      lineinfile:
        path: /etc/motd
        line: 'sudo insights-client --register'
        # line: 'sudo insights-client --payload rhel7-xccdf_org.ssgproject.content_profile_standard --content-type application/vnd.redhat.compliance.something+tgz'
...
