# vagrant ssh
Vagrant.configure("2") do |config|
  config.vm.box = "rhel7_6"
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 1024
    libvirt.cpus = 2
    libvirt.qemu_use_session = false
  end

  config.vm.hostname = "rhel7-insights-client-prod.virbr0.akofink-laptop"
  # config.vm.network "private_network", type: "dhcp"
  # config.vm.synced_folder "~/dev/repos/insights-client", "/home/vagrant/insights-client", type: "nfs", nfs_version: 4
  # config.vm.synced_folder "~/dev/repos/insights-core", "/home/vagrant/insights-core", type: "nfs", nfs_version: 4
  # config.vm.synced_folder "~/dev/repos/compliance-client", "/home/vagrant/compliance-client", type: "nfs", nfs_version: 4
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "insights-client.yml"
    ansible.extra_vars = {
      rhsm_password: ENV['RHSM_PASSWORD'] || 'password'
    }
  end
end
