# vagrant box add --name rhel8_2 rhel-8.2-x86_64-kvm.box
# vagrant ssh -- -A -R 8080:localhost:8080
Vagrant.configure("2") do |config|
  config.vm.box = "rhel8_2"
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 4092
    libvirt.cpus = 2
    libvirt.qemu_use_session = false
  end

  config.vm.hostname = "rhel82-insights-client.virbr0.akofink-laptop"
  # config.vm.network "private_network", type: "dhcp"
  # config.vm.synced_folder "~/dev/repos/insights-client", "/home/vagrant/insights-client", type: "nfs", nfs_version: 4
  # config.vm.synced_folder "~/dev/repos/insights-core", "/home/vagrant/insights-core", type: "nfs", nfs_version: 4
  config.vm.synced_folder "~/dev/repos/insights-client", "/home/vagrant/insights-client"
  config.vm.synced_folder "~/dev/repos/insights-core", "/home/vagrant/insights-core"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "insights-client.yml"
    ansible.verbose = true
    # ansible.raw_arguments = ['-vvvv']
    # ansible.host_vars = {
    #   'default' => {
    #     'ansible_python_interpreter' => '/usr/libexec/platform-python' # only if you use ansible < 2.8
    #   }
    # }
  end
end
